function(osbornex_set_solution_folders)
    set(_vs_presets_folder "Visual Studio Presets")
    set(_orderbook_folder "Orderbook")
    set(_messages_folder "Messages")
    set(_queue_folder "Queue")
    set(_ingress_folder "Ingress")
    set(_sharding_folder "Sharding")
    set(_pubsub_folder "PubSub")
    set(_simulation_folder "Simulation")
    set(_testsupport_folder "TestSupport")
    set(_dependencies_folder "Dependencies")

    foreach(target IN ITEMS ALL_BUILD ZERO_CHECK INSTALL RUN_TESTS)
        if(TARGET ${target})
            set_target_properties(${target} PROPERTIES FOLDER "${_vs_presets_folder}")
        endif()
    endforeach()

    foreach(target IN ITEMS Orderbook OrderbookTest OrderbookBench run-tests run-benchmarks)
        if(TARGET ${target})
            set_target_properties(${target} PROPERTIES FOLDER "${_orderbook_folder}")
        endif()
    endforeach()

    foreach(target IN ITEMS Messages)
        if(TARGET ${target})
            set_target_properties(${target} PROPERTIES FOLDER "${_messages_folder}")
        endif()
    endforeach()

    foreach(target IN ITEMS Queue QueueTest)
        if(TARGET ${target})
            set_target_properties(${target} PROPERTIES FOLDER "${_queue_folder}")
        endif()
    endforeach()

    foreach(target IN ITEMS Ingress IngressTest)
        if(TARGET ${target})
            set_target_properties(${target} PROPERTIES FOLDER "${_ingress_folder}")
        endif()
    endforeach()

    foreach(target IN ITEMS Sharding ShardingTest)
        if(TARGET ${target})
            set_target_properties(${target} PROPERTIES FOLDER "${_sharding_folder}")
        endif()
    endforeach()

    foreach(target IN ITEMS PubSub PubSubTest)
        if(TARGET ${target})
            set_target_properties(${target} PROPERTIES FOLDER "${_pubsub_folder}")
        endif()
    endforeach()

    foreach(target IN ITEMS Simulation SimulationTest SimulationMain)
        if(TARGET ${target})
            set_target_properties(${target} PROPERTIES FOLDER "${_simulation_folder}")
        endif()
    endforeach()

    foreach(target IN ITEMS TestSupport)
        if(TARGET ${target})
            set_target_properties(${target} PROPERTIES FOLDER "${_testsupport_folder}")
        endif()
    endforeach()

    foreach(target IN ITEMS gtest gtest_main gmock gmock_main benchmark benchmark_main)
        if(TARGET ${target})
            set_target_properties(${target} PROPERTIES FOLDER "${_dependencies_folder}")
        endif()
    endforeach()
endfunction()
